name: on-new-code
on:
  push:
    branches:
      - master
      - NODE-2461-ci-coverage
  pull_request:
    branches: '*'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [16]
        os: [ubuntu-latest]
        # node-version: [12, 14, 16, 18]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    name: Test on ${{ matrix.os }} with node v${{ matrix.node-version }}
    steps:
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: Run tests and generate code coverage
      run: npm run test:coverage
    # - name: Send coverage to codecov
    #   uses: codecov/codecov-action@v2
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN}}
    #     files: ./coverage/coverage-summary.json
